# Generated by Django 2.2.1 on 2019-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('localizacao', models.CharField(max_length=120)),
            ],
        ),
    ]
