# Generated by Django 2.2.1 on 2019-05-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_despensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoDespensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('despensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Despensa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
        ),
    ]
