# Generated by Django 2.2.1 on 2019-05-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('modoPreparo', models.TextField()),
                ('tempoExecucao', models.DurationField()),
                ('quantidade', models.IntegerField()),
                ('cliente',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente')),
            ],
        ),
    ]
