# Generated by Django 2.2.1 on 2019-05-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempoExecucao',
            field=models.TimeField(),
        ),
    ]
