# Generated by Django 2.2.1 on 2019-05-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190525_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Receita')),
            ],
        ),
    ]
