# Generated by Django 2.2.1 on 2019-05-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_produtoreceita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Receita')),
            ],
        ),
    ]
